// Sammlung der Sprüche
const sprueche = [
  "Deine Einstellung bestimmt deine Richtung.",
  "Träume groß, arbeite hart, bleib demütig.",
  "Der einzige Weg, etwas zu erreichen, besteht darin, es zu versuchen.",
  "Sei so gut, dass sie nicht an dir vorbeikommen können.",
  "Jeder Tag ist eine neue Chance, besser zu werden.",
  "Erfolg ist kein Zufall, sondern das Ergebnis von Engagement.",
  "Glaube an dich selbst und alles ist möglich.",
  "Die größten Erfolge beginnen mit dem Glauben an sich selbst.",
  "Sei mutig, auch wenn du unsicher bist. Das Leben belohnt den Mutigen.",
  "In der Ruhe liegt die Kraft. Bleib fokussiert und beharrlich.",
  "Hindernisse sind das, was du siehst, wenn du den Blick von deinem Ziel abwendest.",
  "Erfolg ist eine Reise, kein Ausflug.",
  "Handle, als ob es unmöglich wäre zu scheitern.",
  "Chancen sind wie Sonnenaufgänge. Wer zu lange wartet, verpasst sie.",
  "Das Geheimnis des Erfolgs ist, den eigenen Weg zu gehen.",
  "Du bist stärker, als du denkst.",
  "Große Träume erfordern starke Entschlossenheit.",
  "Wenn du es träumen kannst, kannst du es auch tun.",
  "Das Leben belohnt Aktion. Handle jetzt, nicht später.",
  "Die Zukunft gehört denen, die an die Schönheit ihrer Träume glauben.",
  "Erfolg beginnt dort, wo die Komfortzone endet.",
  "Arbeite hart im Stillen, lass deinen Erfolg laut sprechen.",
  "Dein einziger Wettbewerber sollte die Person sein, die du gestern warst.",
  "Sei nicht nur gut, sondern herausragend. Die Extra-Meile lohnt sich immer.",
  "Jeder Tag bietet die Chance, ein bisschen besser zu werden als gestern.",
  "Deine Einstellung ist wie ein Preis, er bestimmt deinen Wert.",
  "Versuche nicht, ein erfolgreicher Mensch zu sein, sondern ein wertvoller.",
  "Sei der CEO deines eigenen Lebens. Manage es wie ein Profi.",
  "Entschlossenheit heute führt zum Erfolg morgen.",
  "Der Schlüssel zum Erfolg ist, sich niemals selbst aufzugeben.",
  "Lächle in Richtung deiner Ziele, und sie werden näher rücken.",
  "Große Dinge kommen nicht aus der Komfortzone.",
  "Träume nicht dein Leben, lebe deinen Traum.",
  "Erfolg ist kein Glück, sondern das Ergebnis von Ausdauer und Entschlossenheit.",
  "Warte nicht auf Gelegenheiten, schaffe sie selbst.",
  "Sei hartnäckig in deinen Zielen, aber flexibel in deinen Methoden.",
  "Kleine Schritte führen zu großen Veränderungen.",
  "Die einzige Grenze für deinen Erfolg ist die, die du dir selbst setzt.",
  "Lass deine Träume größer sein als deine Ängste, und deine Handlungen lauter als deine Worte.",
  "Das Glück liegt nicht im Ziel, sondern im Weg dorthin",
  "Liebe ist der Schlüssel, der alle Türen des Herzens öffnet",
  "Positive Gedanken sind wie Sonnenstrahlen für die Seele",
  "Gute Laune ist der beste Begleiter auf dem Weg zum Erfolg",
  "Das Leben ist ein Spaß, also tanze im Regen und lache im Sturm",
  "Erfolg ist die Summe kleiner Anstrengungen, Tag für Tag",
  "Die Inspiration für Veränderung beginnt in deinem eigenen Herzen",
  "Inmitten einer Blumenwiese blüht die Vielfalt des Lebens",
  "Berge sind die Herausforderungen, die wir erklimmen, um uns selbst zu finden",
  "Fließe wie das Wasser, sei flexibel und finde deinen eigenen Weg",
  "Manchmal sind die besten Momente die, die wir nicht planen",
  "Erfolg beginnt mit einem positiven Gedanken und einem ersten Schritt",
  "In der Liebe finden wir nicht nur uns selbst",
  "Lebe heute, lache jeden Tag und liebe unendlich",
  "Die Sonne scheint immer hinter den Wolken des Zweifels",
  "Gute Laune ist wie ein magischer Schlüssel für verschlossene Türen",
  "Erfolg ist nicht das Ende, sondern ein neuer Anfang",
  "Die Inspiration, nach der du suchst, steckt bereits in dir",
  "Blumenwiesen erinnern uns daran, dass Schönheit überall ist, wo wir hinschauen",
  "Berge sind stille Lehrer, die uns die Größe der Natur und des Lebens zeigen",
  "Wasser erinnert uns daran, dass auch Fließen ein Weg des Fortschritts ist",
  "Das Leben ist wie ein Abenteuer, also schnall den Rucksack an und geh los",
  "Liebe ist die Sprache, die jeder verstehen kann, egal welche Herkunft",
  "In positiven Gedanken finden wir die Kraft, unsere Realität zu formen",
  "Gute Laune ist ansteckend – verbreite sie wie ein Lächeln",
  "Erfolg ist das Ergebnis von Ausdauer, Hingabe und einem Hauch von Risiko",
  "Inspiration ist wie ein Funke, der das Feuer der Kreativität entfacht",
  "Blumenwiesen sind wie Gemälde der Natur, bunt und voller Leben",
  "Berge sind die Gipfel unserer Träume, die wir erklimmen können",
  "Wasser lehrt uns, dass Veränderung der Schlüssel zur Reinheit ist",
  "Im Tanz des Lebens finden wir unseren eigenen Rhythmus",
  "Liebe ist der Duft, den die Blumen der Seele verströmen",
  "Positive Gedanken sind wie Sterne, die die Nacht des Zweifels erhellen",
  "Lass die Musik der guten Laune deine Sorgen vertreiben",
  "Das Leben ist ein Theaterstück – spiele die Hauptrolle mit Leidenschaft",
  "Erfolg ist kein Zufall, sondern das Resultat beharrlicher Arbeit",
  "Die Flügel der Inspiration tragen dich zu neuen Horizonten",
  "Auf der Blumenwiese des Lebens pflücken wir die schönsten Momente",
  "Berge sind nicht nur Hindernisse, sondern auch Gipfel der Erkenntnis",
  "Wie das Wasser im Fluss, fließe gelassen durch die Herausforderungen",
  "Das Ungeplante birgt oft die schönsten Überraschungen",
  "Jeder Tag ist eine leere Leinwand – male ein buntes Bild",
  "Liebe ist das Licht, das die Dunkelheit vertreibt",
  "Lebe heute, als ob es kein Morgen gäbe, liebe, als ob es kein Gestern gab",
  "Die Sonne bricht immer durch, selbst in den dunkelsten Momenten",
  "Gute Laune ist wie ein Regenschirm an trüben Tagen",
  "Erfolg ist die Summe kleiner Siege auf dem Weg zum großen Triumph",
  "Blumenwiesen erinnern uns daran, dass Schönheit aus Vielfalt entsteht",
  "Berge sind stumme Zeugen unserer inneren Stärke",
  "Wasser fließt nicht zurück – geh voran und folge seinem Beispiel",
  "Liebe ist das schönste Geschenk, das wir geben und empfangen können",
  "In der Ruhe der Natur finden wir die Kraft für den Alltag",
  "Die Inspiration ist der Schlüssel zum Tor der Kreativität",
  "Lebe heute, plane für morgen, erinnere dich an gestern",
  "Die kleinen Freuden im Leben sind wie Sterne in der Nacht",
  "Die Liebe zu dir selbst ist der Anfang einer lebenslangen Romanze",
  "Auf dem Berg der Schwierigkeiten liegt oft der Schatz des Erfolgs",
  "In der Tiefe des Wassers spiegelt sich die Klarheit des Geistes",
  "Ein Lächeln kostet nichts, aber es schenkt so viel",
  "Die Blumen des Glücks blühen in den Gärten der Zufriedenheit",
  "Berge erinnern uns daran, dass Höhen und Tiefen das Leben formen",
  "Das Leben ist wie ein Fluss – lass dich von ihm tragen",
  "Liebe ist der nährende Boden, auf dem Beziehungen gedeihen",
  "Erfolg ist wie eine Reise – genieße jeden Schritt",
  "Blumenwiesen sind Poesie der Natur, die das Herz berührt",
  "Berge stehen fest, selbst wenn der Wind des Wandels weht",
  "Wasser lehrt uns, dass Flexibilität der Schlüssel zum Überleben ist",
  "Die Liebe zu sich selbst ist der Anker in stürmischen Zeiten",
  "Jeder Tag ist ein Abenteuer, das darauf wartet, entdeckt zu werden",
  "Erfolg ist das Summen der Harmonie von Fleiß und Leidenschaft",
  "Die Blumen des Glücks wachsen im Garten der Dankbarkeit",
  "Berge erinnern uns daran, dass das Leben Höhen und Tiefen hat",
  "Wasser fließt sanft und überwindet dabei selbst den härtesten Stein",
  "Die Liebe zu sich selbst ist der Schlüssel zur Liebe für andere",
  "Das Leben ist wie ein Gemälde – fülle es mit lebendigen Farben",
  "Erfolg ist der süße Geschmack der Früchte harter Arbeit",
  "Blumenwiesen sind wie bunte Teppiche, die die Natur uns schenkt",
  "Berge sind nicht nur Hindernisse, sondern auch Wege zum Gipfel",
  "Wasser lehrt uns, dass Veränderung das Leben belebt",
  "Träume groß, arbeite hart und höre niemals auf zu glauben.",
  "Der Weg zum Erfolg beginnt mit dem ersten Schritt – also leg los!",
  "In der Mitte von Schwierigkeiten liegt die Möglichkeit.",
  "Erfolg ist kein Zufall, sondern das Ergebnis harter Arbeit und ständiger Weiterentwicklung.",
  "Glaube an dich selbst, und du wirst halbwegs am Ziel sein.",
  "Jeder Tag ist eine neue Chance, dein Bestes zu geben.",
  "Hindernisse sind das, was du siehst, wenn du den Blick von deinem Ziel nimmst.",
  "Die einzige Grenze, die existiert, ist die, die du dir selbst setzt.",
  "Große Dinge beginnen mit kleinen Schritten – also fang einfach an.",
  "Erfolg ist wie ein Eisberg – die meisten sehen nur die Spitze, nicht den Aufwand darunter.",
  "Du bist stärker, als du denkst, mutiger, als du glaubst und klüger, als du dir vorstellen kannst.",
  "Setze Ziele, die so groß sind, dass du dich zwingen musst zu wachsen, um sie zu erreichen.",
  "Deine Einstellung bestimmt deine Richtung – also bleib positiv!",
  "Selbst der längste Weg beginnt mit einem einzigen Schritt.",
  "Erfolg ist keine Glückssache, sondern das Ergebnis beharrlicher Anstrengungen.",
  "Der Schlüssel zum Erfolg liegt darin, zu beginnen, bevor du bereit bist.",
  "Niederlagen sind nur vorübergehend, aber der Verzicht bleibt für immer.",
  "Große Geister haben immer heftige Widerstände von durchschnittlichen Köpfen erlebt.",
  "Die einzige Person, die dich aufhalten kann, bist du selbst.",
  "Der Unterschied zwischen einem Berg und einem Hügel besteht darin, ob du ihn erklimmst oder umgehst – also stürz dich in die Herausforderungen des Lebens.",
  "Träume groß, arbeite hart und höre niemals auf zu glauben",
  "Der Weg zum Erfolg beginnt mit dem ersten Schritt – also leg los",
  "In der Mitte von Schwierigkeiten liegt die Möglichkeit",
  "Erfolg ist kein Zufall, sondern das Ergebnis harter Arbeit und ständiger Weiterentwicklung",
  "Glaube an dich selbst, und du wirst halbwegs am Ziel sein",
  "Jeder Tag ist eine neue Chance, dein Bestes zu geben",
  "Hindernisse sind das, was du siehst, wenn du den Blick von deinem Ziel nimmst",
  "Die einzige Grenze, die existiert, ist die, die du dir selbst setzt",
  "Große Dinge beginnen mit kleinen Schritten – also fang einfach an",
  "Erfolg ist wie ein Eisberg – die meisten sehen nur die Spitze, nicht den Aufwand darunter",
  "Du bist stärker, als du denkst, mutiger, als du glaubst und klüger, als du dir vorstellen kannst",
  "Setze Ziele, die so groß sind, dass du dich zwingen musst zu wachsen, um sie zu erreichen",
  "Deine Einstellung bestimmt deine Richtung – also bleib positiv",
  "Selbst der längste Weg beginnt mit einem einzigen Schritt",
  "Erfolg ist keine Glückssache, sondern das Ergebnis beharrlicher Anstrengungen",
  "Der Schlüssel zum Erfolg liegt darin, zu beginnen, bevor du bereit bist",
  "Niederlagen sind nur vorübergehend, aber der Verzicht bleibt für immer",
  "Große Geister haben immer heftige Widerstände von durchschnittlichen Köpfen erlebt",
  "Die einzige Person, die dich aufhalten kann, bist du selbst",
  "Der Unterschied zwischen einem Berg und einem Hügel besteht darin, ob du ihn erklimmst oder umgehst – also stürz dich in die Herausforderungen des Lebens",
  "Der einzige Weg, großartige Arbeit zu leisten, besteht darin, zu lieben, was du tust. - Steve Jobs",
  "Erfolg ist die Fähigkeit, von einem Misserfolg zum anderen zu gehen, ohne seinen Enthusiasmus zu verlieren. - Winston Churchill",
  "Das Geheimnis des Erfolgs liegt darin, anzufangen. - Mark Twain",
  "Nichts kann dich stoppen, wenn du entschlossen bist, voranzukommen. - Zig Ziglar",
  "Die Zukunft gehört denen, die an die Schönheit ihrer Träume glauben.- Eleanor Roosevelt",
  "Gib jedem Tag die Chance, der schönste deines Lebens zu werden. - Mark Twain",
  "Erfolg besteht darin, von Misserfolg zu Misserfolg zu gehen, ohne seine Begeisterung zu verlieren. - Winston Churchill",
  "Der einzige Weg, großartige Dinge zu tun, ist, sie zu lieben. - Steve Jobs",
  "Die einzige Grenze für unseren Erfolg liegt dort, wo wir aufhören, hinzuschauen. - Albert Einstein",
  "Dein Leben wird nicht besser durch Zufall, sondern durch Veränderung. - Jim Rohn",
  "Wenn du nicht über dich hinausgehst, wirst du nie wissen, wie weit du gehen kannst. - T.S. Eliot",
  "Der Unterschied zwischen einem gewöhnlichen und einem außergewöhnlichen Leben liegt darin, außergewöhnliche Entscheidungen zu treffen. - Unknown",
  "Das Geheimnis des Erfolgs liegt darin, zu wissen, etwas zu tun, zu lieben und darin, niemals aufzugeben. - Bryant McGill",
  "Das größte Vergnügen im Leben besteht darin, das zu tun, von dem die Menschen sagen, du könntest es nicht tun. - Walter Bagehot",
  "Erfolg ist das, was passiert, wenn Vorbereitung auf Gelegenheit trifft. - Seneca",
  "Glaube an dich selbst und alles ist möglich. - Chantal Sutherland",
  "Mache heute so fantastisch, dass gestern neidisch wird. - Unknown",
  "Deine Einstellung bestimmt deine Richtung. - Unknown",
  "Die einzige Möglichkeit, großartige Arbeit zu leisten, ist, das zu lieben, was du tust. - Steve Jobs",
  "Träume groß, arbeite hart und höre niemals auf zu glauben - Steve Jobs",
  "Erfolg ist die Fähigkeit, von einem Misserfolg zum anderen zu gehen, ohne seinen Enthusiasmus zu verlieren - Winston Churchill",
  "Das Geheimnis des Erfolgs liegt darin, anzufangen - Mark Twain",
  "Nichts kann dich stoppen, wenn du entschlossen bist, voranzukommen - Zig Ziglar",
  "Die Zukunft gehört denen, die an die Schönheit ihrer Träume glauben - Eleanor Roosevelt",
  "Gib jedem Tag die Chance, der schönste deines Lebens zu werden - Mark Twain",
  "Erfolg besteht darin, von Misserfolg zu Misserfolg zu gehen, ohne seine Begeisterung zu verlieren - Winston Churchill",
  "Die einzige Grenze für unseren Erfolg liegt dort, wo wir aufhören, hinzuschaue - Albert Einstein",
  "Dein Leben wird nicht besser durch Zufall, sondern durch Veränderung - Jim Rohn",
  "Wenn du nicht über dich hinausgehst, wirst du nie wissen, wie weit du gehen kannst - T.S. Eliot",
  "Der Unterschied zwischen einem gewöhnlichen und einem außergewöhnlichen Leben liegt darin, außergewöhnliche Entscheidungen zu treffen - Unknown",
  "Der Weg zum Erfolg und der Weg zum Misserfolg sind oft ein und derselbe - Colin R. Davis",
  "Das Geheimnis des Erfolgs liegt darin, zu wissen, etwas zu tun, zu lieben und darin, niemals aufzugeben - Bryant McGill",
  "Das größte Vergnügen im Leben besteht darin, das zu tun, von dem die Menschen sagen, du könntest es nicht tun - Walter Bagehot",
  "Erfolg ist das, was passiert, wenn Vorbereitung auf Gelegenheit trifft - Seneca",
  "Glaube an dich selbst und alles ist möglich - Chantal Sutherland",
  "Mache heute so fantastisch, dass gestern neidisch wird - Unknown",
  "Deine Einstellung bestimmt deine Richtung - Unknown",
  "Lebe das Leben, von dem du träumst, und bleibe niemals stehen - Unknownn",
  "In der Ruhe liegt die Kraft – finde Frieden in jedem Moment - Unknown",
  "Sei mutig und habe Vertrauen, denn du bist stärker, als du denkst - Unknown",
  "Akzeptiere Herausforderungen als Chancen zum Wachsen und Lernen - Unknown",
  "Umarme Veränderungen, denn sie führen oft zu den besten Zeiten deines Lebens - Unknown",
  "Dein Potenzial ist grenzenlos – lass dich nicht von Zweifeln einschränken - Unknown",
  


  


      // Weitere Sprüche können hier hinzugefügt werden
    ];
